import { agentsDocKey, decisionsDocKey, parseDocKey } from "./keys.ts";
import { parseSkill } from "./skills.ts";
import type { SyncReport } from "./bridge.ts";
import type { AgentContext, Doc, SyncOutcome } from "./types.ts";

export const MANAGED_START = "<!-- xdev-hive:start (generated by xDev Hive, edit in Hive not here) -->";
export const MANAGED_END = "<!-- xdev-hive:end -->";

/** Files in a repo that are rendered from Hive docs. Agents must propose changes instead of editing them. */
export const PROTECTED_PATHS = ["AGENTS.md", "CLAUDE.md", "docs/decisions.md"] as const;

// Where docs for paths without a folder (e.g. **/*.test.ts) go: Claude Code's path-scoped rules.
export const RULES_DIR = ".claude/rules/xdev-hive";

// Skills from Hive: Claude Code loads .claude/skills/<name>/SKILL.md by itself; a repo's own skills sit next to them.
export const SKILLS_DIR = ".claude/skills";
export const skillFile = (name: string) => `${SKILLS_DIR}/${name}/SKILL.md`;

/** The skills a project's repo gets: the team's, and the project's own, which replace a team skill of the same name. */
export function projectSkills(project: string, docs: Doc[]): Doc[] {
  const byName = new Map<string, Doc>();
  for (const scope of ["org", "project"] as const) {
    for (const d of docs) {
      const k = parseDocKey(d.key);
      if (k.skill && k.scope === scope && (scope === "org" || k.project === project)) byName.set(k.slug, d);
    }
  }
  return [...byName.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([, d]) => d);
}

/** SKILL.md as Claude Code wants it (front matter first), the rest in the managed block. */
function renderSkill(d: Doc): string {
  const front = /^---\r?\n[\s\S]*?\r?\n---[ \t]*(?:\r?\n|$)/.exec(d.content)?.[0] ?? "";
  const body = d.content.slice(front.length).trim();
  return `${front.trimEnd()}\n${MANAGED_START}\n<!-- ${d.key} v${d.version} -->\n\n${body}\n${MANAGED_END}\n`;
}

const skillDescription = (d: Doc): string => {
  try {
    return parseSkill(d.content).description.replace(/\s+/g, " ");
  } catch {
    return "";
  }
};

export interface SyncFile {
  path: string;
  content: string;
  /** content is only the managed block: whatever the file has outside it stays (nested AGENTS.md). */
  block?: boolean;
}

export function stripManaged(md: string): string {
  const start = md.indexOf(MANAGED_START);
  const end = md.indexOf(MANAGED_END);
  if (start === -1 || end === -1 || end < start) return md;
  return (md.slice(0, start) + md.slice(end + MANAGED_END.length)).replace(/^\s+/, "");
}

// The folder of a glob before its first wildcard: "apps/web/**" → "apps/web", "**/*.ts" → "", "src/main.ts" → "src".
export function globDir(glob: string): string {
  const parts = glob.split("/");
  const dir: string[] = [];
  for (let i = 0; i < parts.length - 1 && !/[*?[\]{}]/.test(parts[i]!); i++) dir.push(parts[i]!);
  return dir.join("/");
}

/** Docs limited to paths that this project's repo gets: its own, and org docs meant for AGENTS.md. */
export function scopedDocs(project: string, docs: Doc[]): Doc[] {
  return docs
    .filter((d) => d.paths?.length && (d.scope === "org" ? d.includeInAgents : d.project === project))
    .sort((a, b) => a.key.localeCompare(b.key));
}

const ruleFile = (d: Doc) => `${RULES_DIR}/${d.scope === "org" ? "org-" : ""}${d.key.split("/").at(-1)}.md`;
const docHeader = (d: Doc, globs: string[]) => [`<!-- ${d.key} v${d.version} -->`, `> Applies to ${globs.map((g) => `\`${g}\``).join(", ")}.`, ""];

/** Where each scoped doc goes: a nested AGENTS.md per glob folder, a rules file for globs without one. */
function placements(docs: Doc[]): Array<{ doc: Doc; file: string; globs: string[]; nested: boolean }> {
  const out: Array<{ doc: Doc; file: string; globs: string[]; nested: boolean }> = [];
  for (const doc of docs) {
    const byDir = new Map<string, string[]>();
    for (const g of doc.paths) byDir.set(globDir(g), [...(byDir.get(globDir(g)) ?? []), g]);
    for (const [dir, globs] of [...byDir].sort(([a], [b]) => a.localeCompare(b))) {
      out.push(dir ? { doc, file: `${dir}/AGENTS.md`, globs, nested: true } : { doc, file: ruleFile(doc), globs, nested: false });
    }
  }
  return out;
}

/**
 * AGENTS.md = managed block (project key, org docs flagged includeInAgents, and a list of the docs for
 * some paths, which stay out of this file) followed by the project's own doc.
 */
export function renderAgentsMd(project: string, projectDoc: Doc | null, orgDocs: Doc[]): string {
  const shared = orgDocs
    .filter((d) => d.scope === "org" && d.includeInAgents && !d.paths?.length && !parseDocKey(d.key).skill)
    .sort((a, b) => a.key.localeCompare(b.key));
  const scoped = placements(scopedDocs(project, orgDocs));
  const index = scoped.length
    ? [
        "## Docs for some paths",
        "",
        "Kept out of this file. Before changing files that match, read the doc listed for them:",
        "",
        ...scoped.map((p) => `- ${p.globs.map((g) => `\`${g}\``).join(", ")}: \`${p.file}\` (${p.doc.title})`),
        "",
      ]
    : [];
  const skills = projectSkills(project, orgDocs);
  const skillIndex = skills.length
    ? [
        "## Skills",
        "",
        "How the team does recurring work. Claude Code loads them from `.claude/skills/`; any other agent reads one with `skill_get` (xdev-hive MCP) when its description fits the task:",
        "",
        ...skills.map((d) => `- \`${parseDocKey(d.key).slug}\`: ${skillDescription(d)}`),
        "",
      ]
    : [];
  const block = [
    MANAGED_START,
    `> Hive project key: \`${project}\``,
    "",
    ...shared.flatMap((d) => [`<!-- ${d.key} v${d.version} -->`, d.content.trim(), ""]),
    ...index,
    ...skillIndex,
    MANAGED_END,
  ].join("\n");
  const body = (projectDoc?.content ?? `# ${project}\n`).trim();
  return `${block}\n\n${body}\n`;
}

/**
 * The repo files rendered from Hive docs. Docs for some paths go to a nested AGENTS.md (read by Codex,
 * and by Claude Code when it opens files there) or, for globs without a folder, to a Claude Code rule
 * with the same globs, which other agents find through the list in AGENTS.md.
 */
export function planProjectSync(project: string, docs: Doc[]): SyncFile[] {
  const agents = docs.find((d) => d.key === agentsDocKey(project)) ?? null;
  const decisions = docs.find((d) => d.key === decisionsDocKey(project));
  const files: SyncFile[] = [{ path: "AGENTS.md", content: renderAgentsMd(project, agents, docs) }];
  if (decisions) files.push({ path: "docs/decisions.md", content: `${decisions.content.trim()}\n` });

  const nested = new Map<string, string[]>();
  for (const p of placements(scopedDocs(project, docs))) {
    if (p.nested) {
      nested.set(p.file, [...(nested.get(p.file) ?? []), ...docHeader(p.doc, p.globs), p.doc.content.trim(), ""]);
      continue;
    }
    const front = ["---", "paths:", ...p.globs.map((g) => `  - "${g}"`), "---"];
    files.push({ path: p.file, content: [...front, MANAGED_START, ...docHeader(p.doc, p.globs), p.doc.content.trim(), MANAGED_END, ""].join("\n") });
  }
  for (const [file, lines] of [...nested].sort(([a], [b]) => a.localeCompare(b))) {
    files.push({ path: file, content: [MANAGED_START, ...lines, MANAGED_END].join("\n"), block: true });
  }
  for (const d of projectSkills(project, docs)) files.push({ path: skillFile(parseDocKey(d.key).slug), content: renderSkill(d) });
  return files;
}

/** AGENTS.md longer than this gets a note on sync: move parts of it into docs for some paths. */
export const AGENTS_MD_LINES = 200;

const lineCount = (s: string) => (s ? s.replace(/\n$/, "").split("\n").length : 0);

/**
 * What an agent of the project gets (roadmap 22n, Context agent): the AGENTS.md a sync writes, what it is made of
 * (the team's docs, the project's, the list of docs for some paths, the skills), where the docs for some paths go,
 * and every file the sync writes. Memory counts are the backend's to add.
 */
export function describeProjectContext(project: string, docs: Doc[]): Omit<AgentContext, "memory"> {
  const files = planProjectSync(project, docs);
  const agentsMd = files[0]!.content;
  const agents = docs.find((d) => d.key === agentsDocKey(project)) ?? null;
  const shared = docs
    .filter((d) => d.scope === "org" && d.includeInAgents && !d.paths?.length && !parseDocKey(d.key).skill)
    .sort((a, b) => a.key.localeCompare(b.key));
  const scoped = placements(scopedDocs(project, docs));
  const skills = projectSkills(project, docs);
  const blocks: AgentContext["blocks"] = [
    { kind: "shared", items: shared.map((d) => ({ key: d.key, title: d.title, version: d.version, lines: lineCount(d.content.trim()) + 2 })) },
    { kind: "project", items: [{ key: agentsDocKey(project), title: agents?.title ?? project, version: agents?.version ?? null, lines: lineCount((agents?.content ?? `# ${project}`).trim()) }] },
    ...(scoped.length ? [{ kind: "paths" as const, items: [{ key: null, title: String(scoped.length), version: null, lines: scoped.length + 4 }] }] : []),
    ...(skills.length ? [{ kind: "skills" as const, items: [{ key: null, title: String(skills.length), version: null, lines: skills.length + 4 }] }] : []),
  ];
  return {
    project,
    agentsMd,
    lines: lineCount(agentsMd),
    limit: AGENTS_MD_LINES,
    blocks,
    paths: scoped.map((p) => ({ key: p.doc.key, title: p.doc.title, globs: p.globs, file: p.file, nested: p.nested })),
    files: [...files.map((f) => ({ path: f.path, lines: lineCount(f.content), block: Boolean(f.block) })), { path: "CLAUDE.md", lines: 1, block: false }],
  };
}

/** A managed block in front of what the file already has outside it. */
export function withManagedBlock(existing: string | null, block: string): string {
  const rest = existing ? stripManaged(existing).trim() : "";
  return rest ? `${block}\n\n${rest}\n` : `${block}\n`;
}

/** Claude Code reads CLAUDE.md, so it imports AGENTS.md. Other content in CLAUDE.md is kept. */
export function ensureClaudeImport(existing: string | null): string {
  if (!existing?.trim()) return "@AGENTS.md\n";
  if (/^@AGENTS\.md\s*$/m.test(existing)) return existing;
  return `@AGENTS.md\n\n${existing}`;
}

/** The command id a sync request of a project gets: one open request per machine and project. */
export const syncItemId = (project: string) => `sync:${project}`;

/** A sync as a machine reports it back to the hub (roadmap 22n); the file list is what the web shows. */
export function syncOutcome(report: SyncReport): SyncOutcome {
  return {
    changed: report.files.filter((f) => f.action !== "unchanged" && f.action !== "skipped").map((f) => f.file),
    skipped: report.files.filter((f) => f.action === "skipped").map((f) => f.file),
    commit: report.commit,
    mirrored: report.mirror ? report.mirror.changed.length : null,
    note: report.note ?? null,
  };
}

/** A sync command's output read back; null for a failed one (its output is the error) or one from elsewhere. */
export function readSyncOutcome(output: string | null): SyncOutcome | null {
  if (!output?.startsWith("{")) return null;
  try {
    const o = JSON.parse(output) as Partial<SyncOutcome>;
    return Array.isArray(o.changed) && Array.isArray(o.skipped)
      ? { changed: o.changed, skipped: o.skipped, commit: o.commit ?? null, mirrored: o.mirrored ?? null, note: o.note ?? null }
      : null;
  } catch {
    return null;
  }
}
