import { agentsDocKey, decisionsDocKey } from "./keys.ts";
import type { Doc } from "./types.ts";

export const MANAGED_START = "<!-- xdev-hive:start (generated by xDev Hive, edit in Hive not here) -->";
export const MANAGED_END = "<!-- xdev-hive:end -->";

/** Files in a repo that are rendered from Hive docs. Agents must propose changes instead of editing them. */
export const PROTECTED_PATHS = ["AGENTS.md", "CLAUDE.md", "docs/decisions.md"] as const;

export interface SyncFile {
  path: string;
  content: string;
}

export function stripManaged(md: string): string {
  const start = md.indexOf(MANAGED_START);
  const end = md.indexOf(MANAGED_END);
  if (start === -1 || end === -1 || end < start) return md;
  return (md.slice(0, start) + md.slice(end + MANAGED_END.length)).replace(/^\s+/, "");
}

/** AGENTS.md = managed block (project key + org docs flagged includeInAgents) followed by the project's own doc. */
export function renderAgentsMd(project: string, projectDoc: Doc | null, orgDocs: Doc[]): string {
  const shared = orgDocs
    .filter((d) => d.scope === "org" && d.includeInAgents)
    .sort((a, b) => a.key.localeCompare(b.key));
  const block = [
    MANAGED_START,
    `> Hive project key: \`${project}\``,
    "",
    ...shared.flatMap((d) => [`<!-- ${d.key} v${d.version} -->`, d.content.trim(), ""]),
    MANAGED_END,
  ].join("\n");
  const body = (projectDoc?.content ?? `# ${project}\n`).trim();
  return `${block}\n\n${body}\n`;
}

export function planProjectSync(project: string, docs: Doc[]): SyncFile[] {
  const agents = docs.find((d) => d.key === agentsDocKey(project)) ?? null;
  const decisions = docs.find((d) => d.key === decisionsDocKey(project));
  const files: SyncFile[] = [{ path: "AGENTS.md", content: renderAgentsMd(project, agents, docs) }];
  if (decisions) files.push({ path: "docs/decisions.md", content: `${decisions.content.trim()}\n` });
  return files;
}

/** Claude Code reads CLAUDE.md, so it imports AGENTS.md. Other content in CLAUDE.md is kept. */
export function ensureClaudeImport(existing: string | null): string {
  if (!existing?.trim()) return "@AGENTS.md\n";
  if (/^@AGENTS\.md\s*$/m.test(existing)) return existing;
  return `@AGENTS.md\n\n${existing}`;
}
