import type { AddressInfo } from "node:net";
import { createHubApp } from "#web/app.ts";
import { TokenStore } from "#web/tokens.ts";
import { UserStore } from "#web/users.ts";
import assert from "node:assert/strict";
import { it } from "node:test";
import { SqliteHive } from "@xdev-hive/core/node";
import type { Actor, HiveEvent } from "@xdev-hive/core";
import { Automation } from "#web/automation.ts";
import { adminSession, authHeaders } from "./session.ts";
const admin: Actor = { name: "admin", role: "admin" };
const event = { type: "alert.opened", project: "demo", alert: { severity: "high", id: 1 } } as HiveEvent;
const input = { name: "Incident", project: "demo", trigger: "alert.opened", enabled: true,
  conditions: [{ path: "alert.severity", equals: "high" }], action: { method: "tasks.create", input: { project: "demo", id: "INC-1", title: "Investigate" } } };
it("filters, dry-runs without writes, deduplicates concurrently, and audits execution", async () => {
  const hive = new SqliteHive(":memory:");
  try {
    const automation = new Automation(hive, () => admin);
    const rule = automation.save(input, "owner", admin);
    assert.equal(automation.dryRun(rule.id, event).matches, true);
    assert.throws(() => automation.dryRun(rule.id, undefined as never), /Event is required/);
    assert.equal(automation.dryRun(rule.id, { ...event, project: "other" } as HiveEvent).matches, false);
    assert.equal((await hive.call("tasks.list", {}, admin)).length, 0);
    await automation.onEvent({ ...event, automation: true });
    assert.equal(automation.history().length, 0);
    await Promise.all([automation.onEvent(event), automation.onEvent(event)]);
    assert.equal((await hive.call("tasks.list", {}, admin)).length, 1);
    await automation.onEvent({ ...event, alert: { ...(event as Extract<HiveEvent, { type: "alert.opened" }>).alert, lastSeenAt: "later" } } as HiveEvent);
    assert.equal(automation.history().length, 1);
    assert.equal(automation.history()[0]!.status, "done");
    const runEvent = { type: "run.failed", project: "demo", run: { machine: "m1", runId: "R-1", taskId: "T-1", taskTitle: "Fix", role: "coder", error: "fail", kind: "failed", profileId: null, mrUrl: null, mrIid: null } } as HiveEvent;
    const runRule = automation.save({ ...input, trigger: "run.failed", conditions: [], action: { method: "tasks.create", input: { project: "demo", id: "FIX-1", title: "Fix" } } }, "owner", admin);
    await Promise.all([automation.onEvent(runEvent), automation.onEvent({ ...runEvent, run: { ...(runEvent as Extract<HiveEvent, { type: "run.failed" }>).run, error: "different message" } } as HiveEvent)]);
    assert.equal(automation.history().filter(h => (h as { rule_id: number }).rule_id === runRule.id).length, 1);
    assert.throws(() => automation.save({ ...input, action: { ...input.action, input: { ...input.action.input, project: "other" } } }, "owner", admin));
    assert.throws(() => automation.save({ ...input, action: { method: "agents.stop", input: {} } }, "owner", admin));
  } finally { hive.close(); }
});
it("checks the current owner, supports bounded retries and pause, refuses changed actions", async () => {
  const hive = new SqliteHive(":memory:");
  try {
    let owner: Actor | null = null;
    const automation = new Automation(hive, () => owner);
    const rule = automation.save(input, "owner", admin);
    await automation.onEvent(event);
    const id = Number(automation.history()[0]!.id);
    assert.equal(automation.history()[0]!.status, "failed");
    automation.save({ ...rule, enabled: false }, "owner", admin);
    await assert.rejects(automation.retry(id), /paused/);
    automation.save({ ...rule, action: { ...input.action, input: { ...input.action.input, title: "Changed" } } }, "owner", admin);
    await assert.rejects(automation.retry(id), /changed/);
    automation.save(rule, "owner", admin);
    owner = { name: "owner", role: "viewer" };
    await automation.retry(id);
    assert.equal(automation.history()[0]!.status, "failed");
    owner = admin;
    await automation.retry(id);
    assert.equal(automation.history()[0]!.status, "done");
    await assert.rejects(automation.retry(id));
  } finally { hive.close(); }
});
it("marks interrupted executions uncertain instead of duplicating a possible side effect", () => {
  const hive = new SqliteHive(":memory:");
  try {
    const automation = new Automation(hive, () => admin);
    automation.save(input, "owner", admin);
    hive.db.prepare("INSERT INTO automation_runs(rule_id,event_key,event,rule_body,status,updated_at) VALUES (1,'key','{}','{}','running','now')").run();
    const restarted = new Automation(hive, () => admin);
    assert.equal(restarted.history()[0]!.status, "uncertain");
  } finally { hive.close(); }
});
it("suppresses a real pending memory event generated by automation", async () => {
  const pending: Promise<void>[] = [];
  let automation: Automation;
  const seen: HiveEvent[] = [];
  const hive = new SqliteHive(":memory:", { memoryRequiresApproval: true, onEvent: event => { seen.push(event); pending.push(automation.onEvent(event)); } });
  try {
    automation = new Automation(hive, () => ({ name: "agent", role: "agent" }));
    const action = { method: "memory.write", input: { project: "demo", kind: "context", content: "Investigate incident" } };
    automation.save({ ...input, conditions: [], action }, "owner", admin);
    automation.save({ ...input, trigger: "memory.pending", conditions: [], action }, "owner", admin);
    await automation.onEvent(event);
    await Promise.all(pending);
    assert.equal(seen[0]?.type, "memory.pending");
    assert.equal(seen[0]?.automation, true);
    assert.equal(automation.history().length, 1);
  } finally { hive.close(); }
});
it("exposes management RPC only to hub admins and rejects revoked owners at execution", async () => {
  const hive = new SqliteHive(":memory:");
  const tokens = new TokenStore(hive.db);
  const users = new UserStore(hive.db);
  // Spec 79a: a hub admin is a person signed in on the page; the rule they save is owned by their account.
  const who = { token: adminSession(users, "ops") };
  const viewer = tokens.create("viewer", "viewer");
  const automation = new Automation(hive, owner => {
    const user = owner.startsWith("user:") ? users.get(owner.slice(5)) : null;
    return user && !user.disabled ? { name: user.username, role: "admin", account: user.username } : null;
  });
  const server = createHubApp({ hive, tokens, users, allowedHosts: ["127.0.0.1"], automation }).listen(0, "127.0.0.1");
  await new Promise(resolve => server.once("listening", resolve));
  const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const rpc = async (token: string, method: string, input: unknown = {}) => {
    const response = await fetch(`${base}/api/rpc`, { method: "POST", headers: { "content-type": "application/json", ...authHeaders(token) }, body: JSON.stringify({ method, input }) });
    return { status: response.status, body: await response.json() as { result: { id: number; matches: boolean; length: number } } };
  };
  try {
    for (const method of ["list", "history", "save", "dryRun", "retry"]) assert.equal((await rpc(viewer.token, `automation.${method}`, input)).status, 403);
    const saved = await rpc(who.token, "automation.save", input);
    assert.equal(saved.status, 200);
    assert.equal((await rpc(who.token, "automation.dryRun", { id: saved.body.result.id, event })).body.result.matches, true);
    assert.equal((await rpc(who.token, "automation.dryRun", { id: saved.body.result.id })).status, 400);
    assert.equal(((await rpc(who.token, "automation.list")).body.result as unknown as unknown[]).length, 1);
    assert.equal((await rpc(who.token, "automation.history")).body.result.length, 0);
    const backup = { token: adminSession(users, "backup") };
    users.update(users.list().find((u) => u.username === "ops")!.id, { disabled: true });
    await automation.onEvent(event);
    assert.equal(automation.history()[0]!.status, "failed");
    assert.equal(automation.history()[0]!.error, "forbidden");
    const retryRes = await rpc(backup.token, "automation.retry", { id: automation.history()[0]!.id });
    assert.equal(retryRes.status, 200);
    assert.equal((retryRes.body as unknown as { result: { status: string } }).result.status, "failed");
  } finally {
    await new Promise<void>((resolve, reject) => server.close(e => e ? reject(e) : resolve()));
    hive.close();
  }
});
it("rechecks agent policy and emergency stop on manual retry", async () => {
  const hive = new SqliteHive(":memory:");
  try {
    const automation = new Automation(hive, () => admin);
    automation.save(input, "owner", admin);
    await hive.call("agentPolicy.set", { project: "demo", policy: { autonomy: "read" } }, admin);
    await automation.onEvent(event);
    const id = Number(automation.history()[0]!.id);
    assert.equal(automation.history()[0]!.status, "failed");
    await hive.call("agentPolicy.set", { project: "demo", policy: null }, admin);
    await hive.call("agents.stop", { project: "demo" }, admin);
    await automation.retry(id);
    assert.equal(automation.history()[0]!.status, "failed");
    await hive.call("agents.resume", { project: "demo" }, admin);
    await automation.retry(id);
    assert.equal(automation.history()[0]!.status, "done");
  } finally { hive.close(); }
});
