// A CLI opened on a whole system (GROUP-cli): one session over every repo of the system this machine has, instead of
// one terminal per repo. It starts in the group's root folder (D:/Codes/ehospital-ai), each repo is added with the CLI's
// own flag, and the system's context (its docs, its repos with their keys and folders, the ones missing here) is written
// beside them, never into a repo, so nothing of it lands in a commit. No Electron imports.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { memberFolder, type DesktopProject, type Doc, type HiveSystem } from "@xdev-hive/core";
import { suggestRoot } from "#desktop/main/system-init.ts";

/** First line of every file the app writes for a system's session: what it may overwrite next time, and nothing else. */
export const SYSTEM_CONTEXT_MARK = "<!-- xdev-hive:system-context (generated by xDev Hive when a CLI opens on a system; edit the system's docs in Hive, not here) -->";
const CLAUDE_IMPORT = "@AGENTS.md\n";

export interface SystemWorkspace {
  /** Where the CLI starts and the context is written. */
  cwd: string;
  /** The repos of the system this machine has, in the group's tree order. */
  repos: Array<{ project: string; dir: string; folder: string[] }>;
  /** Members this machine has no repo for: listed for the person, never in the way of opening. */
  missing: Array<{ project: string; pathWithNamespace: string | null }>;
}

/** The deepest folder above every one of `dirs`; null when that is a drive's root or the home folder, which says nothing. */
export function commonParent(dirs: string[], home: string): string | null {
  if (!dirs.length) return null;
  const split = (d: string) => path.resolve(d).split(path.sep);
  let common = split(dirs[0]!).slice(0, -1);
  for (const d of dirs.slice(1)) {
    const parts = split(d);
    let i = 0;
    while (i < common.length && i < parts.length && common[i]!.toLowerCase() === parts[i]!.toLowerCase()) i++;
    common = common.slice(0, i);
  }
  const dir = common.join(path.sep) || path.sep;
  return dir === path.parse(dir).root || path.resolve(dir) === path.resolve(home) ? null : dir;
}

/**
 * Where a system's session starts. The group's root this machine set up (or where the tree says its clones sit, or the
 * folder above all of them) when the context can go there: not inside a repository, and with no AGENTS.md or CLAUDE.md
 * of someone else's. Otherwise, and for a system with one repo here, the app's own folder for the system, with every
 * repo added from there: the first repo itself would put the system's context into that repo's working tree.
 */
export function systemWorkspace(
  system: HiveSystem,
  projects: DesktopProject[],
  opts: { root?: string | null; home: string; sessionDir: string; insideRepo(dir: string): boolean },
): SystemWorkspace {
  const order = [...system.projects].sort((a, b) => memberFolder(system.source, a).join("/").localeCompare(memberFolder(system.source, b).join("/")) || a.localeCompare(b));
  const repos = order.flatMap((project) => {
    const local = projects.find((p) => p.name === project);
    return local && existsSync(local.repo) ? [{ project, dir: path.resolve(local.repo), folder: memberFolder(system.source, project) }] : [];
  });
  const missing = order.filter((p) => !repos.some((r) => r.project === p)).map((project) => ({
    project,
    pathWithNamespace: system.source?.members.find((m) => m.project === project)?.pathWithNamespace ?? null,
  }));
  const given = opts.root && existsSync(opts.root) ? path.resolve(opts.root) : null;
  const root = given ?? suggestRoot(system, projects) ?? (repos.length > 1 ? commonParent(repos.map((r) => r.dir), opts.home) : null);
  const usable = root && existsSync(root) && !opts.insideRepo(root) && contextIsOurs(root) && !repos.some((r) => r.dir === root);
  return { cwd: usable ? root : opts.sessionDir, repos, missing };
}

const read = (file: string) => (existsSync(file) ? readFileSync(file, "utf8") : null);

/** The context files in `dir` are absent or the app's own from an earlier session. */
export function contextIsOurs(dir: string): boolean {
  const agents = read(path.join(dir, "AGENTS.md"));
  const claude = read(path.join(dir, "CLAUDE.md"));
  const gemini = read(path.join(dir, ".gemini", "settings.json"));
  return (agents === null || agents.startsWith(SYSTEM_CONTEXT_MARK)) && (claude === null || claude === CLAUDE_IMPORT) && (gemini === null || gemini.includes("HIVE_SYSTEM"));
}

/** The first line of a project's own AGENTS doc that says what the repo is, for the list of repos. */
export function repoRole(doc: Doc | null): string {
  const line = (doc?.content ?? "").split("\n").map((l) => l.trim()).find((l) => l && !l.startsWith("#") && !l.startsWith(">") && !l.startsWith("<!--"));
  return line ? (line.length > 160 ? `${line.slice(0, 157)}…` : line) : "";
}

const cell = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

/**
 * AGENTS.md of a system's session: which repo is which project (every Hive tool takes the key), where each one is on
 * this machine, what it is for, which are missing, then the system's own docs and the team's, as a repo's AGENTS.md has.
 */
export function renderSystemContext(system: HiveSystem, ws: SystemWorkspace, docs: { system: Doc[]; org: Doc[] }, roles: Record<string, string>): string {
  const everyAgent = (list: Doc[]) => list.filter((d) => d.includeInAgents && !d.paths?.length).sort((a, b) => a.key.localeCompare(b.key));
  const lines = [
    SYSTEM_CONTEXT_MARK,
    `# System ${system.name}`,
    "",
    `> Hive system: \`${system.name}\`. Each repo below is its own Hive project: pass its key as \`project\` to every \`task_*\`, \`memory_*\` and \`doc_*\` tool, and work in that repo's folder (branch \`ai/<task-id>\` there).`,
    ...(system.source ? ["", `Source: ${system.source.forge === "github" ? "GitHub" : "GitLab"} group \`${system.source.groupPath}\` (${system.source.url}).`] : []),
    "",
    "## Repos on this machine",
    "",
    "| Project key | Folder | Subgroup | What it is |",
    "| --- | --- | --- | --- |",
    ...ws.repos.map((r) => `| \`${r.project}\` | \`${cell(r.dir)}\` | ${r.folder.length ? `\`${r.folder.join("/")}\`` : ""} | ${cell(roles[r.project] ?? "")} |`),
    "",
  ];
  if (ws.missing.length) {
    lines.push(
      "## Repos missing on this machine",
      "",
      ...ws.missing.map((m) => `- \`${m.project}\`${m.pathWithNamespace ? ` (\`${m.pathWithNamespace}\`)` : ""}`),
      "",
      "Tell the person before working on them: xDev Hive → Services & tools → \"Set up the group on this machine\" clones them in the group's tree.",
      "",
    );
  }
  const systemDocs = everyAgent(docs.system);
  if (systemDocs.length) lines.push("## The system's docs", "", ...systemDocs.flatMap((d) => [`<!-- ${d.key} v${d.version} -->`, d.content.trim(), ""]));
  const orgDocs = everyAgent(docs.org);
  if (orgDocs.length) lines.push("## The team's conventions", "", ...orgDocs.flatMap((d) => [`<!-- ${d.key} v${d.version} -->`, d.content.trim(), ""]));
  return `${lines.join("\n").trimEnd()}\n`;
}

/**
 * Writes the session's context into `cwd`: AGENTS.md (Codex, and Gemini through its settings), CLAUDE.md importing it,
 * and Gemini's settings with Hive's server for the system. Only files that are absent or the app's own are written.
 */
export function writeSystemContext(cwd: string, agentsMd: string, gemini: { mcpServers: Record<string, unknown> }): string[] {
  mkdirSync(cwd, { recursive: true });
  const written: string[] = [];
  const put = (rel: string, content: string) => {
    const file = path.join(cwd, rel);
    if (read(file) === content) return;
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, content);
    written.push(rel);
  };
  if (!contextIsOurs(cwd)) return written;
  put("AGENTS.md", agentsMd);
  put("CLAUDE.md", CLAUDE_IMPORT);
  put(path.join(".gemini", "settings.json"), `${JSON.stringify({ contextFileName: ["AGENTS.md"], mcpServers: gemini.mcpServers }, null, 2)}\n`);
  return written;
}
